export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "商品id",
      "prop": "id",
      "showColumn": false,
      "editDisplay": false,
      "addDisplay": false
    },	  {
      "type": "input",
      "label": "商品标题",
      "prop": "title",
      search: true
    },	  {
      "type": "input",
      "label": "商品卖点",
      "prop": "sellPoint"
    },	  {
      "type": "number",
      "label": "商品价格",
      "prop": "price"
    },	  {
      "type": "number",
      "label": "库存数量",
      "prop": "num"
    },	  {
      "type": "number",
      "label": "售卖数量限制",
      "prop": "limitNum"
    },	  {
      "type": "input",
      "label": "商品图片",
      "prop": "image"
    },	  {
      "type": "input",
      "label": "所属分类",
      "prop": "cid"
    },	  {
      "label": "商品状态",
      "prop": "status",
      type: 'select',
      dicUrl: '/admin/dict/type/item_status'
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "created",
      "addDisplay": false,
      "editDisabled": true
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updated",
      "addDisplay": false,
      "editDisabled": true
    }  ]
}
