export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "",
      "prop": "id",
      "showColumn": false,
      "editDisplay": false,
      "addDisplay": false
    },	  {
      "type": "input",
      "label": "名称",
      "prop": "name"
    },	  {
      "type": "input",
      "label": "完整路径",
      "prop": "fullUrl"
    },	  {
      "type": "number",
      "label": "排序序号",
      "prop": "sortOrder"
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "created",
      "addDisplay": false,
      "editDisabled": true
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updated",
      "addDisplay": false,
      "editDisabled": true
    },	  {
      "type": "input",
      "label": "逻辑删除",
      "prop": "delFlag",
      "showColumn": false,
      "editDisplay": false,
      "addDisplay": false
    }  ]
}
